import Head from 'next/head';

const Container = (props) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta className="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-w-screen min-h-screen bg-gray-200 flex items-center justify-center px-5 py-5">
        <div className="bg-white text-gray-800 rounded-xl shadow-lg overflow-hidden relative flex" >
          <div className="bg-white h-full w-full px-5 pt-6 pb-10 overflow-y-auto">
            { props.children }
          </div>
        </div>
      </div>
    </div>    
  )
}

export default Container;