import Head from 'next/head'
import { useCallback, useState } from 'react';
import Web3 from "web3";

export default function Home() {
  const [webProvider, setWebProvider] = useState(null);
  const [error, setError] = useState('');
  const [balance, setBalance] = useState('');

  const getBalance = async () => {
 
  if (typeof window.ethereum !== 'undefined') {
      try {
        const accounts = await ethereum.request({ method: "eth_requestAccounts" })
        let web3 = new Web3(ethereum)
        setWebProvider(web3)
        const balance = await web3?.eth?.getBalance(accounts[0])
        setBalance(balance);
      } catch (err) {
        console.log(err)
      }
    } else {
      setError("Please install MetaMask")
    }
  };

  const onClick = useCallback(() => {

    getBalance()

  }, []);

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="w-screen h-screen bg-gray-200 flex align-middle items-center">
          <div className="mx-auto h-64 w-64 bg-white items-center text-center">
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
              onClick={onClick}>
              Connect to MetaMask
            </button>
            {balance && <p>Balance</p>}
            {balance && webProvider && <h2>{webProvider.utils.fromWei(`${balance}`)}</h2>}
            {error && <h2>{error}</h2>}
          </div>
        </div>
      </main>
    </div>
  )
};
